// Copyright 2022 Prysmatic Labs.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: proto/engine/v1/execution_engine.proto

package enginev1

import (
	_ "github.com/OffchainLabs/prysm/v6/proto/eth/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadStatus_Status int32

const (
	PayloadStatus_UNKNOWN            PayloadStatus_Status = 0
	PayloadStatus_VALID              PayloadStatus_Status = 1
	PayloadStatus_INVALID            PayloadStatus_Status = 2
	PayloadStatus_SYNCING            PayloadStatus_Status = 3
	PayloadStatus_ACCEPTED           PayloadStatus_Status = 4
	PayloadStatus_INVALID_BLOCK_HASH PayloadStatus_Status = 5
)

// Enum value maps for PayloadStatus_Status.
var (
	PayloadStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "VALID",
		2: "INVALID",
		3: "SYNCING",
		4: "ACCEPTED",
		5: "INVALID_BLOCK_HASH",
	}
	PayloadStatus_Status_value = map[string]int32{
		"UNKNOWN":            0,
		"VALID":              1,
		"INVALID":            2,
		"SYNCING":            3,
		"ACCEPTED":           4,
		"INVALID_BLOCK_HASH": 5,
	}
)

func (x PayloadStatus_Status) Enum() *PayloadStatus_Status {
	p := new(PayloadStatus_Status)
	*p = x
	return p
}

func (x PayloadStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_v1_execution_engine_proto_enumTypes[0].Descriptor()
}

func (PayloadStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_engine_v1_execution_engine_proto_enumTypes[0]
}

func (x PayloadStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadStatus_Status.Descriptor instead.
func (PayloadStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{12, 0}
}

type ExecutionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient  []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot  []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom     []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao    []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayload) Reset() {
	*x = ExecutionPayload{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayload) ProtoMessage() {}

func (x *ExecutionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayload.ProtoReflect.Descriptor instead.
func (*ExecutionPayload) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPayload) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayload) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayload) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayload) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayload) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayload) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayload) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayload) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayload) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayload) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayload) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayload) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayload) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayload) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ExecutionPayloadCapella struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient  []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot  []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom     []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao    []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// MAX_WITHDRAWALS_PER_PAYLOAD
	Withdrawals   []*Withdrawal `protobuf:"bytes,15,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"` // New in Capella.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadCapella) Reset() {
	*x = ExecutionPayloadCapella{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadCapella) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadCapella) ProtoMessage() {}

func (x *ExecutionPayloadCapella) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadCapella.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadCapella) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionPayloadCapella) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadCapella) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadCapella) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadCapella) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadCapella) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecutionPayloadCapella) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type ExecutionPayloadDeneb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient  []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot  []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom     []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao    []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// MAX_WITHDRAWALS_PER_PAYLOAD
	Withdrawals   []*Withdrawal `protobuf:"bytes,15,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	BlobGasUsed   uint64        `protobuf:"varint,16,opt,name=blob_gas_used,json=blobGasUsed,proto3" json:"blob_gas_used,omitempty"`
	ExcessBlobGas uint64        `protobuf:"varint,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3" json:"excess_blob_gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadDeneb) Reset() {
	*x = ExecutionPayloadDeneb{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadDeneb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadDeneb) ProtoMessage() {}

func (x *ExecutionPayloadDeneb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadDeneb.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadDeneb) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionPayloadDeneb) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadDeneb) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadDeneb) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadDeneb) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadDeneb) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *ExecutionPayloadDeneb) GetBlobGasUsed() uint64 {
	if x != nil {
		return x.BlobGasUsed
	}
	return 0
}

func (x *ExecutionPayloadDeneb) GetExcessBlobGas() uint64 {
	if x != nil {
		return x.ExcessBlobGas
	}
	return 0
}

type ExecutionPayloadCapellaWithValue struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Payload       *ExecutionPayloadCapella `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Value         []byte                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadCapellaWithValue) Reset() {
	*x = ExecutionPayloadCapellaWithValue{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadCapellaWithValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadCapellaWithValue) ProtoMessage() {}

func (x *ExecutionPayloadCapellaWithValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadCapellaWithValue.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadCapellaWithValue) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionPayloadCapellaWithValue) GetPayload() *ExecutionPayloadCapella {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionPayloadCapellaWithValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecutionPayloadDenebAndBlobsBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *ExecutionPayloadDeneb `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	BlobsBundle   *BlobsBundle           `protobuf:"bytes,2,opt,name=blobs_bundle,json=blobsBundle,proto3" json:"blobs_bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadDenebAndBlobsBundle) Reset() {
	*x = ExecutionPayloadDenebAndBlobsBundle{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadDenebAndBlobsBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadDenebAndBlobsBundle) ProtoMessage() {}

func (x *ExecutionPayloadDenebAndBlobsBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadDenebAndBlobsBundle.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadDenebAndBlobsBundle) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionPayloadDenebAndBlobsBundle) GetPayload() *ExecutionPayloadDeneb {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionPayloadDenebAndBlobsBundle) GetBlobsBundle() *BlobsBundle {
	if x != nil {
		return x.BlobsBundle
	}
	return nil
}

type ExecutionPayloadDenebWithValueAndBlobsBundle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Payload               *ExecutionPayloadDeneb `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Value                 []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	BlobsBundle           *BlobsBundle           `protobuf:"bytes,3,opt,name=blobs_bundle,json=blobsBundle,proto3" json:"blobs_bundle,omitempty"`
	ShouldOverrideBuilder bool                   `protobuf:"varint,4,opt,name=should_override_builder,json=shouldOverrideBuilder,proto3" json:"should_override_builder,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) Reset() {
	*x = ExecutionPayloadDenebWithValueAndBlobsBundle{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadDenebWithValueAndBlobsBundle) ProtoMessage() {}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadDenebWithValueAndBlobsBundle.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadDenebWithValueAndBlobsBundle) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) GetPayload() *ExecutionPayloadDeneb {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) GetBlobsBundle() *BlobsBundle {
	if x != nil {
		return x.BlobsBundle
	}
	return nil
}

func (x *ExecutionPayloadDenebWithValueAndBlobsBundle) GetShouldOverrideBuilder() bool {
	if x != nil {
		return x.ShouldOverrideBuilder
	}
	return false
}

type ExecutionPayloadHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient     []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot        []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot     []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom        []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao       []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit         uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData        []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas    []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash        []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionsRoot []byte                 `protobuf:"bytes,14,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPayloadHeader) Reset() {
	*x = ExecutionPayloadHeader{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadHeader) ProtoMessage() {}

func (x *ExecutionPayloadHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadHeader.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadHeader) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionPayloadHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

type ExecutionPayloadHeaderCapella struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient     []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot        []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot     []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom        []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao       []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit         uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData        []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas    []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash        []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionsRoot []byte                 `protobuf:"bytes,14,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	WithdrawalsRoot  []byte                 `protobuf:"bytes,15,opt,name=withdrawals_root,json=withdrawalsRoot,proto3" json:"withdrawals_root,omitempty"` // New in Capella.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPayloadHeaderCapella) Reset() {
	*x = ExecutionPayloadHeaderCapella{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadHeaderCapella) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadHeaderCapella) ProtoMessage() {}

func (x *ExecutionPayloadHeaderCapella) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadHeaderCapella.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadHeaderCapella) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionPayloadHeaderCapella) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadHeaderCapella) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadHeaderCapella) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeaderCapella) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadHeaderCapella) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderCapella) GetWithdrawalsRoot() []byte {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

type ExecutionPayloadHeaderDeneb struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient     []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot        []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot     []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom        []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao       []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit         uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData        []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas    []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash        []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionsRoot []byte                 `protobuf:"bytes,14,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	WithdrawalsRoot  []byte                 `protobuf:"bytes,15,opt,name=withdrawals_root,json=withdrawalsRoot,proto3" json:"withdrawals_root,omitempty"`
	BlobGasUsed      uint64                 `protobuf:"varint,16,opt,name=blob_gas_used,json=blobGasUsed,proto3" json:"blob_gas_used,omitempty"`
	ExcessBlobGas    uint64                 `protobuf:"varint,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3" json:"excess_blob_gas,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPayloadHeaderDeneb) Reset() {
	*x = ExecutionPayloadHeaderDeneb{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadHeaderDeneb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadHeaderDeneb) ProtoMessage() {}

func (x *ExecutionPayloadHeaderDeneb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadHeaderDeneb.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadHeaderDeneb) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionPayloadHeaderDeneb) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadHeaderDeneb) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadHeaderDeneb) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeaderDeneb) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadHeaderDeneb) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetWithdrawalsRoot() []byte {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderDeneb) GetBlobGasUsed() uint64 {
	if x != nil {
		return x.BlobGasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeaderDeneb) GetExcessBlobGas() uint64 {
	if x != nil {
		return x.ExcessBlobGas
	}
	return 0
}

type PayloadAttributes struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevRandao            []byte                 `protobuf:"bytes,2,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	SuggestedFeeRecipient []byte                 `protobuf:"bytes,3,opt,name=suggested_fee_recipient,json=suggestedFeeRecipient,proto3" json:"suggested_fee_recipient,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PayloadAttributes) Reset() {
	*x = PayloadAttributes{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttributes) ProtoMessage() {}

func (x *PayloadAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAttributes.ProtoReflect.Descriptor instead.
func (*PayloadAttributes) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{9}
}

func (x *PayloadAttributes) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PayloadAttributes) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *PayloadAttributes) GetSuggestedFeeRecipient() []byte {
	if x != nil {
		return x.SuggestedFeeRecipient
	}
	return nil
}

type PayloadAttributesV2 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevRandao            []byte                 `protobuf:"bytes,2,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	SuggestedFeeRecipient []byte                 `protobuf:"bytes,3,opt,name=suggested_fee_recipient,json=suggestedFeeRecipient,proto3" json:"suggested_fee_recipient,omitempty"`
	Withdrawals           []*Withdrawal          `protobuf:"bytes,4,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"` // New in Capella.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PayloadAttributesV2) Reset() {
	*x = PayloadAttributesV2{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttributesV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttributesV2) ProtoMessage() {}

func (x *PayloadAttributesV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAttributesV2.ProtoReflect.Descriptor instead.
func (*PayloadAttributesV2) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{10}
}

func (x *PayloadAttributesV2) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PayloadAttributesV2) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *PayloadAttributesV2) GetSuggestedFeeRecipient() []byte {
	if x != nil {
		return x.SuggestedFeeRecipient
	}
	return nil
}

func (x *PayloadAttributesV2) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type PayloadAttributesV3 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevRandao            []byte                 `protobuf:"bytes,2,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	SuggestedFeeRecipient []byte                 `protobuf:"bytes,3,opt,name=suggested_fee_recipient,json=suggestedFeeRecipient,proto3" json:"suggested_fee_recipient,omitempty"`
	Withdrawals           []*Withdrawal          `protobuf:"bytes,4,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	ParentBeaconBlockRoot []byte                 `protobuf:"bytes,5,opt,name=parent_beacon_block_root,json=parentBeaconBlockRoot,proto3" json:"parent_beacon_block_root,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PayloadAttributesV3) Reset() {
	*x = PayloadAttributesV3{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttributesV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttributesV3) ProtoMessage() {}

func (x *PayloadAttributesV3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAttributesV3.ProtoReflect.Descriptor instead.
func (*PayloadAttributesV3) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{11}
}

func (x *PayloadAttributesV3) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PayloadAttributesV3) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *PayloadAttributesV3) GetSuggestedFeeRecipient() []byte {
	if x != nil {
		return x.SuggestedFeeRecipient
	}
	return nil
}

func (x *PayloadAttributesV3) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *PayloadAttributesV3) GetParentBeaconBlockRoot() []byte {
	if x != nil {
		return x.ParentBeaconBlockRoot
	}
	return nil
}

type PayloadStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          PayloadStatus_Status   `protobuf:"varint,1,opt,name=status,proto3,enum=ethereum.engine.v1.PayloadStatus_Status" json:"status,omitempty"`
	LatestValidHash []byte                 `protobuf:"bytes,2,opt,name=latest_valid_hash,json=latestValidHash,proto3" json:"latest_valid_hash,omitempty"`
	ValidationError string                 `protobuf:"bytes,3,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayloadStatus) Reset() {
	*x = PayloadStatus{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadStatus) ProtoMessage() {}

func (x *PayloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadStatus.ProtoReflect.Descriptor instead.
func (*PayloadStatus) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{12}
}

func (x *PayloadStatus) GetStatus() PayloadStatus_Status {
	if x != nil {
		return x.Status
	}
	return PayloadStatus_UNKNOWN
}

func (x *PayloadStatus) GetLatestValidHash() []byte {
	if x != nil {
		return x.LatestValidHash
	}
	return nil
}

func (x *PayloadStatus) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

type ForkchoiceState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HeadBlockHash      []byte                 `protobuf:"bytes,1,opt,name=head_block_hash,json=headBlockHash,proto3" json:"head_block_hash,omitempty"`
	SafeBlockHash      []byte                 `protobuf:"bytes,2,opt,name=safe_block_hash,json=safeBlockHash,proto3" json:"safe_block_hash,omitempty"`
	FinalizedBlockHash []byte                 `protobuf:"bytes,3,opt,name=finalized_block_hash,json=finalizedBlockHash,proto3" json:"finalized_block_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForkchoiceState) Reset() {
	*x = ForkchoiceState{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkchoiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkchoiceState) ProtoMessage() {}

func (x *ForkchoiceState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkchoiceState.ProtoReflect.Descriptor instead.
func (*ForkchoiceState) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ForkchoiceState) GetHeadBlockHash() []byte {
	if x != nil {
		return x.HeadBlockHash
	}
	return nil
}

func (x *ForkchoiceState) GetSafeBlockHash() []byte {
	if x != nil {
		return x.SafeBlockHash
	}
	return nil
}

func (x *ForkchoiceState) GetFinalizedBlockHash() []byte {
	if x != nil {
		return x.FinalizedBlockHash
	}
	return nil
}

// The withdrawal receipt with the recipient address and amount withdrawn
type Withdrawal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Withdrawal index for accounting purposes
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Validator index for the withdrawal
	ValidatorIndex uint64 `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	// The execution address receiving the funds
	Address []byte `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// The withdrawn amount in Gwei
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{14}
}

func (x *Withdrawal) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Withdrawal) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *Withdrawal) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Withdrawal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// BlobsBundle is retrieved through engine-api from the execution layer client.
// It consists of the necessary components for constructing blob sidecars
// objects to gossip through p2p.
type BlobsBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The KZG commitments of the blobs.
	KzgCommitments [][]byte `protobuf:"bytes,1,rep,name=kzg_commitments,json=kzgCommitments,proto3" json:"kzg_commitments,omitempty"`
	// The proofs of the blobs.
	Proofs [][]byte `protobuf:"bytes,2,rep,name=proofs,proto3" json:"proofs,omitempty"`
	// The blobs itself.
	Blobs         [][]byte `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobsBundle) Reset() {
	*x = BlobsBundle{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobsBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobsBundle) ProtoMessage() {}

func (x *BlobsBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobsBundle.ProtoReflect.Descriptor instead.
func (*BlobsBundle) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{15}
}

func (x *BlobsBundle) GetKzgCommitments() [][]byte {
	if x != nil {
		return x.KzgCommitments
	}
	return nil
}

func (x *BlobsBundle) GetProofs() [][]byte {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *BlobsBundle) GetBlobs() [][]byte {
	if x != nil {
		return x.Blobs
	}
	return nil
}

// BlobsBundleV2 is retrieved through engine-api from the execution layer client.
// It consists of the necessary components for constructing data column sidecars
// objects to gossip through p2p.
// It is introduced in Fulu network upgrade.
type BlobsBundleV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KzgCommitments [][]byte               `protobuf:"bytes,1,rep,name=kzg_commitments,json=kzgCommitments,proto3" json:"kzg_commitments,omitempty"`
	Proofs         [][]byte               `protobuf:"bytes,2,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Blobs          [][]byte               `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlobsBundleV2) Reset() {
	*x = BlobsBundleV2{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobsBundleV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobsBundleV2) ProtoMessage() {}

func (x *BlobsBundleV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobsBundleV2.ProtoReflect.Descriptor instead.
func (*BlobsBundleV2) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{16}
}

func (x *BlobsBundleV2) GetKzgCommitments() [][]byte {
	if x != nil {
		return x.KzgCommitments
	}
	return nil
}

func (x *BlobsBundleV2) GetProofs() [][]byte {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *BlobsBundleV2) GetBlobs() [][]byte {
	if x != nil {
		return x.Blobs
	}
	return nil
}

// Blob contains the data that is to be committed on chain.
type Blob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blob bytes.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{17}
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// BlobAndProofV2 consists of the blob and the cell proofs for each cell in the blob.
type BlobAndProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	KzgProof      []byte                 `protobuf:"bytes,2,opt,name=kzg_proof,json=kzgProof,proto3" json:"kzg_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobAndProof) Reset() {
	*x = BlobAndProof{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobAndProof) ProtoMessage() {}

func (x *BlobAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobAndProof.ProtoReflect.Descriptor instead.
func (*BlobAndProof) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{18}
}

func (x *BlobAndProof) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *BlobAndProof) GetKzgProof() []byte {
	if x != nil {
		return x.KzgProof
	}
	return nil
}

// BlobAndProofV2 consists of the blob and the cell proofs for each cell in the blob.
// It is introduced in Fulu network upgrade.
type BlobAndProofV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	KzgProofs     [][]byte               `protobuf:"bytes,2,rep,name=kzg_proofs,json=kzgProofs,proto3" json:"kzg_proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobAndProofV2) Reset() {
	*x = BlobAndProofV2{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobAndProofV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobAndProofV2) ProtoMessage() {}

func (x *BlobAndProofV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobAndProofV2.ProtoReflect.Descriptor instead.
func (*BlobAndProofV2) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{19}
}

func (x *BlobAndProofV2) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *BlobAndProofV2) GetKzgProofs() [][]byte {
	if x != nil {
		return x.KzgProofs
	}
	return nil
}

type IncludableBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlobIndex     uint32                 `protobuf:"varint,2,opt,name=blob_index,json=blobIndex,proto3" json:"blob_index,omitempty"`
	Blob          []byte                 `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	KzgCommitment []byte                 `protobuf:"bytes,4,opt,name=kzg_commitment,json=kzgCommitment,proto3" json:"kzg_commitment,omitempty"`
	CellProofs    [][]byte               `protobuf:"bytes,5,rep,name=cell_proofs,json=cellProofs,proto3" json:"cell_proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncludableBlob) Reset() {
	*x = IncludableBlob{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludableBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludableBlob) ProtoMessage() {}

func (x *IncludableBlob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludableBlob.ProtoReflect.Descriptor instead.
func (*IncludableBlob) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{20}
}

func (x *IncludableBlob) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *IncludableBlob) GetBlobIndex() uint32 {
	if x != nil {
		return x.BlobIndex
	}
	return 0
}

func (x *IncludableBlob) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *IncludableBlob) GetKzgCommitment() []byte {
	if x != nil {
		return x.KzgCommitment
	}
	return nil
}

func (x *IncludableBlob) GetCellProofs() [][]byte {
	if x != nil {
		return x.CellProofs
	}
	return nil
}

var File_proto_engine_v1_execution_engine_proto protoreflect.FileDescriptor

const file_proto_engine_v1_execution_engine_proto_rawDesc = "" +
	"\n" +
	"&proto/engine/v1/execution_engine.proto\x12\x12ethereum.engine.v1\x1a\x1bproto/eth/ext/options.proto\"\xe1\x04\n" +
	"\x10ExecutionPayload\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x12A\n" +
	"\ftransactions\x18\x0e \x03(\fB\x1d\x8a\xb5\x18\x03?,?\x92\xb5\x18\x121048576,1073741824R\ftransactions\"\xbf\x05\n" +
	"\x17ExecutionPayloadCapella\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x12A\n" +
	"\ftransactions\x18\x0e \x03(\fB\x1d\x8a\xb5\x18\x03?,?\x92\xb5\x18\x121048576,1073741824R\ftransactions\x12U\n" +
	"\vwithdrawals\x18\x0f \x03(\v2\x1e.ethereum.engine.v1.WithdrawalB\x13\x92\xb5\x18\x0fwithdrawal.sizeR\vwithdrawals\"\x89\x06\n" +
	"\x15ExecutionPayloadDeneb\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x12A\n" +
	"\ftransactions\x18\x0e \x03(\fB\x1d\x8a\xb5\x18\x03?,?\x92\xb5\x18\x121048576,1073741824R\ftransactions\x12U\n" +
	"\vwithdrawals\x18\x0f \x03(\v2\x1e.ethereum.engine.v1.WithdrawalB\x13\x92\xb5\x18\x0fwithdrawal.sizeR\vwithdrawals\x12\"\n" +
	"\rblob_gas_used\x18\x10 \x01(\x04R\vblobGasUsed\x12&\n" +
	"\x0fexcess_blob_gas\x18\x11 \x01(\x04R\rexcessBlobGas\"\x7f\n" +
	" ExecutionPayloadCapellaWithValue\x12E\n" +
	"\apayload\x18\x01 \x01(\v2+.ethereum.engine.v1.ExecutionPayloadCapellaR\apayload\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xae\x01\n" +
	"#ExecutionPayloadDenebAndBlobsBundle\x12C\n" +
	"\apayload\x18\x01 \x01(\v2).ethereum.engine.v1.ExecutionPayloadDenebR\apayload\x12B\n" +
	"\fblobs_bundle\x18\x02 \x01(\v2\x1f.ethereum.engine.v1.BlobsBundleR\vblobsBundle\"\x85\x02\n" +
	",ExecutionPayloadDenebWithValueAndBlobsBundle\x12C\n" +
	"\apayload\x18\x01 \x01(\v2).ethereum.engine.v1.ExecutionPayloadDenebR\apayload\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12B\n" +
	"\fblobs_bundle\x18\x03 \x01(\v2\x1f.ethereum.engine.v1.BlobsBundleR\vblobsBundle\x126\n" +
	"\x17should_override_builder\x18\x04 \x01(\bR\x15shouldOverrideBuilder\"\xd9\x04\n" +
	"\x16ExecutionPayloadHeader\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x123\n" +
	"\x11transactions_root\x18\x0e \x01(\fB\x06\x8a\xb5\x18\x0232R\x10transactionsRoot\"\x93\x05\n" +
	"\x1dExecutionPayloadHeaderCapella\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x123\n" +
	"\x11transactions_root\x18\x0e \x01(\fB\x06\x8a\xb5\x18\x0232R\x10transactionsRoot\x121\n" +
	"\x10withdrawals_root\x18\x0f \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fwithdrawalsRoot\"\xdd\x05\n" +
	"\x1bExecutionPayloadHeaderDeneb\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0220R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x122\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\x13\x8a\xb5\x18\x0flogs_bloom.sizeR\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x122\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x13\x92\xb5\x18\x0fextra_data.sizeR\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x123\n" +
	"\x11transactions_root\x18\x0e \x01(\fB\x06\x8a\xb5\x18\x0232R\x10transactionsRoot\x121\n" +
	"\x10withdrawals_root\x18\x0f \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fwithdrawalsRoot\x12\"\n" +
	"\rblob_gas_used\x18\x10 \x01(\x04R\vblobGasUsed\x12&\n" +
	"\x0fexcess_blob_gas\x18\x11 \x01(\x04R\rexcessBlobGas\"\x9a\x01\n" +
	"\x11PayloadAttributes\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12'\n" +
	"\vprev_randao\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12>\n" +
	"\x17suggested_fee_recipient\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0220R\x15suggestedFeeRecipient\"\xf3\x01\n" +
	"\x13PayloadAttributesV2\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12'\n" +
	"\vprev_randao\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12>\n" +
	"\x17suggested_fee_recipient\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0220R\x15suggestedFeeRecipient\x12U\n" +
	"\vwithdrawals\x18\x04 \x03(\v2\x1e.ethereum.engine.v1.WithdrawalB\x13\x92\xb5\x18\x0fwithdrawal.sizeR\vwithdrawals\"\xb4\x02\n" +
	"\x13PayloadAttributesV3\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12'\n" +
	"\vprev_randao\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12>\n" +
	"\x17suggested_fee_recipient\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0220R\x15suggestedFeeRecipient\x12U\n" +
	"\vwithdrawals\x18\x04 \x03(\v2\x1e.ethereum.engine.v1.WithdrawalB\x13\x92\xb5\x18\x0fwithdrawal.sizeR\vwithdrawals\x12?\n" +
	"\x18parent_beacon_block_root\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\x15parentBeaconBlockRoot\"\x92\x02\n" +
	"\rPayloadStatus\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.ethereum.engine.v1.PayloadStatus.StatusR\x06status\x122\n" +
	"\x11latest_valid_hash\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0flatestValidHash\x12)\n" +
	"\x10validation_error\x18\x03 \x01(\tR\x0fvalidationError\"`\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05VALID\x10\x01\x12\v\n" +
	"\aINVALID\x10\x02\x12\v\n" +
	"\aSYNCING\x10\x03\x12\f\n" +
	"\bACCEPTED\x10\x04\x12\x16\n" +
	"\x12INVALID_BLOCK_HASH\x10\x05\"\xab\x01\n" +
	"\x0fForkchoiceState\x12.\n" +
	"\x0fhead_block_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\rheadBlockHash\x12.\n" +
	"\x0fsafe_block_hash\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\rsafeBlockHash\x128\n" +
	"\x14finalized_block_hash\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\x12finalizedBlockHash\"\xd5\x01\n" +
	"\n" +
	"Withdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12w\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04BN\x82\xb5\x18Jgithub.com/OffchainLabs/prysm/v6/consensus-types/primitives.ValidatorIndexR\x0evalidatorIndex\x12 \n" +
	"\aaddress\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0220R\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\"\xe0\x01\n" +
	"\vBlobsBundle\x12N\n" +
	"\x0fkzg_commitments\x18\x01 \x03(\fB%\x8a\xb5\x18\x04?,48\x92\xb5\x18\x19max_blob_commitments.sizeR\x0ekzgCommitments\x12=\n" +
	"\x06proofs\x18\x02 \x03(\fB%\x8a\xb5\x18\x04?,48\x92\xb5\x18\x19max_blob_commitments.sizeR\x06proofs\x12B\n" +
	"\x05blobs\x18\x03 \x03(\fB,\x8a\xb5\x18\v?,blob.size\x92\xb5\x18\x19max_blob_commitments.sizeR\x05blobs\"\xe4\x01\n" +
	"\rBlobsBundleV2\x12N\n" +
	"\x0fkzg_commitments\x18\x01 \x03(\fB%\x8a\xb5\x18\x04?,48\x92\xb5\x18\x19max_blob_commitments.sizeR\x0ekzgCommitments\x12?\n" +
	"\x06proofs\x18\x02 \x03(\fB'\x8a\xb5\x18\x04?,48\x92\xb5\x18\x1bmax_cell_proofs_length.sizeR\x06proofs\x12B\n" +
	"\x05blobs\x18\x03 \x03(\fB,\x8a\xb5\x18\v?,blob.size\x92\xb5\x18\x19max_blob_commitments.sizeR\x05blobs\")\n" +
	"\x04Blob\x12!\n" +
	"\x04data\x18\x01 \x01(\fB\r\x8a\xb5\x18\tblob.sizeR\x04data\"V\n" +
	"\fBlobAndProof\x12!\n" +
	"\x04blob\x18\x01 \x01(\fB\r\x8a\xb5\x18\tblob.sizeR\x04blob\x12#\n" +
	"\tkzg_proof\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0248R\bkzgProof\"y\n" +
	"\x0eBlobAndProofV2\x12!\n" +
	"\x04blob\x18\x01 \x01(\fB\r\x8a\xb5\x18\tblob.sizeR\x04blob\x12D\n" +
	"\n" +
	"kzg_proofs\x18\x02 \x03(\fB%\x8a\xb5\x18\x0248\x92\xb5\x18\x1bmax_cell_proofs_length.sizeR\tkzgProofs\"\xea\x01\n" +
	"\x0eIncludableBlob\x12\x1f\n" +
	"\atx_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x06txHash\x12\x1d\n" +
	"\n" +
	"blob_index\x18\x02 \x01(\rR\tblobIndex\x12!\n" +
	"\x04blob\x18\x03 \x01(\fB\r\x8a\xb5\x18\tblob.sizeR\x04blob\x12-\n" +
	"\x0ekzg_commitment\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0248R\rkzgCommitment\x12F\n" +
	"\vcell_proofs\x18\x05 \x03(\fB%\x8a\xb5\x18\x0248\x92\xb5\x18\x1bmax_cell_proofs_length.sizeR\n" +
	"cellProofsB\x95\x01\n" +
	"\x16org.ethereum.engine.v1B\x14ExecutionEngineProtoP\x01Z9github.com/OffchainLabs/prysm/v6/proto/engine/v1;enginev1\xaa\x02\x12Ethereum.Engine.V1\xca\x02\x12Ethereum\\Engine\\v1b\x06proto3"

var (
	file_proto_engine_v1_execution_engine_proto_rawDescOnce sync.Once
	file_proto_engine_v1_execution_engine_proto_rawDescData []byte
)

func file_proto_engine_v1_execution_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_v1_execution_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_v1_execution_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_v1_execution_engine_proto_rawDesc), len(file_proto_engine_v1_execution_engine_proto_rawDesc)))
	})
	return file_proto_engine_v1_execution_engine_proto_rawDescData
}

var file_proto_engine_v1_execution_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_engine_v1_execution_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_engine_v1_execution_engine_proto_goTypes = []any{
	(PayloadStatus_Status)(0),                            // 0: ethereum.engine.v1.PayloadStatus.Status
	(*ExecutionPayload)(nil),                             // 1: ethereum.engine.v1.ExecutionPayload
	(*ExecutionPayloadCapella)(nil),                      // 2: ethereum.engine.v1.ExecutionPayloadCapella
	(*ExecutionPayloadDeneb)(nil),                        // 3: ethereum.engine.v1.ExecutionPayloadDeneb
	(*ExecutionPayloadCapellaWithValue)(nil),             // 4: ethereum.engine.v1.ExecutionPayloadCapellaWithValue
	(*ExecutionPayloadDenebAndBlobsBundle)(nil),          // 5: ethereum.engine.v1.ExecutionPayloadDenebAndBlobsBundle
	(*ExecutionPayloadDenebWithValueAndBlobsBundle)(nil), // 6: ethereum.engine.v1.ExecutionPayloadDenebWithValueAndBlobsBundle
	(*ExecutionPayloadHeader)(nil),                       // 7: ethereum.engine.v1.ExecutionPayloadHeader
	(*ExecutionPayloadHeaderCapella)(nil),                // 8: ethereum.engine.v1.ExecutionPayloadHeaderCapella
	(*ExecutionPayloadHeaderDeneb)(nil),                  // 9: ethereum.engine.v1.ExecutionPayloadHeaderDeneb
	(*PayloadAttributes)(nil),                            // 10: ethereum.engine.v1.PayloadAttributes
	(*PayloadAttributesV2)(nil),                          // 11: ethereum.engine.v1.PayloadAttributesV2
	(*PayloadAttributesV3)(nil),                          // 12: ethereum.engine.v1.PayloadAttributesV3
	(*PayloadStatus)(nil),                                // 13: ethereum.engine.v1.PayloadStatus
	(*ForkchoiceState)(nil),                              // 14: ethereum.engine.v1.ForkchoiceState
	(*Withdrawal)(nil),                                   // 15: ethereum.engine.v1.Withdrawal
	(*BlobsBundle)(nil),                                  // 16: ethereum.engine.v1.BlobsBundle
	(*BlobsBundleV2)(nil),                                // 17: ethereum.engine.v1.BlobsBundleV2
	(*Blob)(nil),                                         // 18: ethereum.engine.v1.Blob
	(*BlobAndProof)(nil),                                 // 19: ethereum.engine.v1.BlobAndProof
	(*BlobAndProofV2)(nil),                               // 20: ethereum.engine.v1.BlobAndProofV2
	(*IncludableBlob)(nil),                               // 21: ethereum.engine.v1.IncludableBlob
}
var file_proto_engine_v1_execution_engine_proto_depIdxs = []int32{
	15, // 0: ethereum.engine.v1.ExecutionPayloadCapella.withdrawals:type_name -> ethereum.engine.v1.Withdrawal
	15, // 1: ethereum.engine.v1.ExecutionPayloadDeneb.withdrawals:type_name -> ethereum.engine.v1.Withdrawal
	2,  // 2: ethereum.engine.v1.ExecutionPayloadCapellaWithValue.payload:type_name -> ethereum.engine.v1.ExecutionPayloadCapella
	3,  // 3: ethereum.engine.v1.ExecutionPayloadDenebAndBlobsBundle.payload:type_name -> ethereum.engine.v1.ExecutionPayloadDeneb
	16, // 4: ethereum.engine.v1.ExecutionPayloadDenebAndBlobsBundle.blobs_bundle:type_name -> ethereum.engine.v1.BlobsBundle
	3,  // 5: ethereum.engine.v1.ExecutionPayloadDenebWithValueAndBlobsBundle.payload:type_name -> ethereum.engine.v1.ExecutionPayloadDeneb
	16, // 6: ethereum.engine.v1.ExecutionPayloadDenebWithValueAndBlobsBundle.blobs_bundle:type_name -> ethereum.engine.v1.BlobsBundle
	15, // 7: ethereum.engine.v1.PayloadAttributesV2.withdrawals:type_name -> ethereum.engine.v1.Withdrawal
	15, // 8: ethereum.engine.v1.PayloadAttributesV3.withdrawals:type_name -> ethereum.engine.v1.Withdrawal
	0,  // 9: ethereum.engine.v1.PayloadStatus.status:type_name -> ethereum.engine.v1.PayloadStatus.Status
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_engine_v1_execution_engine_proto_init() }
func file_proto_engine_v1_execution_engine_proto_init() {
	if File_proto_engine_v1_execution_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_v1_execution_engine_proto_rawDesc), len(file_proto_engine_v1_execution_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_engine_v1_execution_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_v1_execution_engine_proto_depIdxs,
		EnumInfos:         file_proto_engine_v1_execution_engine_proto_enumTypes,
		MessageInfos:      file_proto_engine_v1_execution_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_v1_execution_engine_proto = out.File
	file_proto_engine_v1_execution_engine_proto_goTypes = nil
	file_proto_engine_v1_execution_engine_proto_depIdxs = nil
}
